filmsatlas/films/urls.py
from django.urls import re_path, include
import films.views as films

app_name = 'films'

urlpatterns = [
    re_path('$', films.index, name='index'),
    re_path('genres/$', films.genres, name='genres'),
    re_path('genre/(?P<genre>.*\s*)/$', films.genre, name='genre'),
    re_path('sort-year/(?P<year>.*\s*)/$', films.year, name='year'),
    re_path('sort-country/(?P<country>.*\s*)/$', films.country, name='country'),
    re_path('collections/$', films.collections, name='collections'),
    re_path('collection/(?P<collection>.*\s*)/$', films.collection, name='collection'),
    re_path('films/page/(?P<page>\d+)/$', films.films_page, name='films_page'),
    re_path('film/(?P<film>.*\s*)/$', films.film, name='film'),
    re_path('search/(?P<search>.*\s*)/$', films.search, name='search'),
    re_path('country/(?P<country>.*\s*)/$', films.country, name='country'),
    re_path('films/api/', include('films.apiurls', namespace='apiurls')),


]

filmsatlas/filmsatlas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('films.urls', namespace='films')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filmsatlas/films/models.py
from django.db import models

# Create your models here.


class Genre(models.Model):
    name = models.CharField(verbose_name='Жанры', unique=True, max_length=100)
    desc = models.TextField(verbose_name='Описание', blank=True)
    img = models.ImageField(verbose_name='Картинка', blank=True, upload_to='ganre_img')
    seo_desc = models.TextField(verbose_name='Сео описание', blank=True)

    def __str__(self):
        return f'{self.name}'

    def self_name(self):
        context = str(self.name)
        return context

    def check_genres(self):
        films = GenreFilm.objects.filter(genre_id=self.id)[:6]
        name = self.name[0].upper()+self.name[1:]
        context_films = [obj.film.check_film() for obj in films]
        context = {
            'name': name,
            'desc': self.desc,
            'films': context_films if context_films else "",
        }
        return context

    def json_dump_genre(self, quantity):
        if quantity:
            films = GenreFilm.objects.filter(genre_id=self.id)[:10]
        else:
            films = GenreFilm.objects.filter(genre_id=self.id)
        context_films = [obj.film.json_dump_film() for obj in films]
        context = {
            'genre': self.name,
            'films': context_films if context_films else "",
        }
        return context

    class Meta:
        ordering = ['name']
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Country(models.Model):
    name = models.CharField(verbose_name='Страна', unique=True, max_length=150)

    def __str__(self):
        return f'{self.name}'

    def self_name(self):
        context = str(self.name)
        return context

    def json_dump_country(self):
        films = CountryFilm.objects.filter(country=self.id)
        context_films = [obj.film.json_dump_film() for obj in films]
        context = {
            'country': self.name,
            'films': context_films if context_films else "",
        }
        return context

    class Meta:
        ordering = ['name']
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Collection(models.Model):
    name = models.CharField(verbose_name='Подборка', unique=True, max_length=100)
    desc = models.TextField(verbose_name='Описание', blank=True)
    img = models.ImageField(verbose_name='Картинка', blank=True, upload_to='ganre_img')
    seo_desc = models.TextField(verbose_name='Сео описание', blank=True)
    sort = models.SmallIntegerField(verbose_name='Сортировка', default=0)

    def __str__(self):
        return f'{self.name}'

    def check_filmcollection(self):
        collectionsfilm = CollectionFilm.objects.filter(collection_id=self.id)
        return collectionsfilm

    def json_dump_country(self, quantity):
        if quantity:
            films = CollectionFilm.objects.filter(collection_id=self.id)[:10]
        else:
            films = CollectionFilm.objects.filter(collection_id=self.id)
        context_films = [obj.film.json_dump_film() for obj in films]
        context ={
            'collection': self.name,
            'films': context_films if context_films else ""
        }
        return context

    class Meta:
        ordering = ['name']
        verbose_name = 'Подборка'
        verbose_name_plural = 'Подборки'


class Film(models.Model):
    name = models.CharField(verbose_name='Название фильма', max_length=150)
    duration = models.CharField(verbose_name='Продолжительность', max_length=150, blank=True)
    year_of_release = models.DateField(verbose_name='Дата выпуска', default='2000-01-01', blank=True)
    age = models.SmallIntegerField(verbose_name='Возраст', default=0, blank=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    image = models.ImageField(verbose_name='Картинка', upload_to='film_img', blank=True)
    link_trailer = models.URLField(verbose_name='Ссылка на трейлер', blank=True)
    rating_kp = models.CharField(verbose_name='Рейтинг кп', max_length=10, blank=True)
    rating_imdb = models.CharField(verbose_name='Рейтинг imdb', max_length=10, blank=True)
    date_add = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True)
    seo_desc = models.TextField(verbose_name='Сео описание', blank=True)
    saw = models.IntegerField(verbose_name='Просмотры', default=0, blank=True)
    rating_fa = models.IntegerField(verbose_name='Рейтинг fa', default=0, blank=True)

    def __str__(self):
        return f'{self.name}'

    def check_film(self):
        genre = GenreFilm.objects.filter(film_id=self.id)
        country = CountryFilm.objects.filter(film_id=self.id)
        context_country = [obj.country.name for obj in country]
        context_genre = [obj.genre.name for obj in genre]
        context = {
            'name': self.name,
            'year_of_release': str(self.year_of_release),
            'duration': self.duration,
            'image': str(self.image.url if self.image else ""),
            'description': self.description if self.description else "",
            'genre': context_genre if context_genre else "",
            'country': context_country if context_country else "",
        }
        return context

    def check_collectionfilm(self):
        collectionsfilm = CollectionFilm.objects.filter(film_id=self.id)
        return collectionsfilm

    def check_country(self):
        country = CountryFilm.objects.filter(film_id=self.id)
        return country

    def check_ganre(self):
        genre = GenreFilm.objects.filter(film_id=self.id)
        return genre

    def check_linkfilm(self):
        linkfilm = LinkFilm.objects.filter(film_id=self.id)
        return linkfilm

    def json_dump_film(self):
        genre = GenreFilm.objects.filter(film_id=self.id)
        country = CountryFilm.objects.filter(film_id=self.id)
        context_country = [obj.json_dump_country() for obj in country]
        context_genre = [obj.json_dump_genre() for obj in genre]
        context={
            'name': self.name,
            'year_of_release': str(self.year_of_release),
            'duration': self.duration,
            'image': str(self.image.url if self.image else ""),
            'description': self.description if self.description else "",
            'genre': context_genre if context_genre else "",
            'context_country': context_country if context_country else "",
        }
        return context

    class Meta:
        ordering = ['year_of_release', 'saw', 'name', 'rating_imdb']
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class CountryFilm(models.Model):
    country = models.ForeignKey(Country, verbose_name='Страна', related_name='country', on_delete=models.CASCADE)
    film = models.ForeignKey(Film, verbose_name='Фильм', related_name='country_film', on_delete=models.CASCADE)

    def json_dump_country(self):
        return f'{self.country.name}'


class LinkFilm(models.Model):
    name = models.ForeignKey(Film, verbose_name='Фильм', related_name='link_film', on_delete=models.CASCADE)
    link_film = models.URLField(verbose_name='Ссылка на фильм', blank=True)


class GenreFilm(models.Model):
    genre = models.ForeignKey(Genre, verbose_name='Жанр', related_name='genre', on_delete=models.CASCADE)
    film = models.ForeignKey(Film, verbose_name='Фильм', related_name='genre_film', on_delete=models.CASCADE)

    def json_dump_genre(self):
        return f'{self.genre.name}'

    def json_dump_films(self):
        context = {
            'name': self.film.name,
            'image': str(self.film.image.url if self.film.image else ""),
            'year_of_release': str(self.film.year_of_release),
            'duration': self.film.duration,
        }
        return context


class CollectionFilm(models.Model):
    collection = models.ForeignKey(Collection, verbose_name='Подборка', related_name='collection', on_delete=models.CASCADE)
    film = models.ForeignKey(Film, verbose_name='Фильм', related_name='collection_film', on_delete=models.CASCADE)

filmsatlas/films/forms.py
import django.forms as forms
from .models import Film, GenreFilm, LinkFilm, CountryFilm, CollectionFilm, Genre, Collection, Country


class CreateGenre(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ('name', 'desc', 'img', 'seo_desc')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CreateCountry(forms.ModelForm):
    class Meta:
        model = Country
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class CreateFilm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

filmsatlas/films/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse
from django.template.context_processors import csrf
from .models import Film, GenreFilm, LinkFilm, CountryFilm, CollectionFilm, Collection, Country, Genre
# Create your views here.
from django.core.paginator import Paginator


def index(request):
    if request.method == 'GET':
        films = Film.objects.all().order_by('year_of_release', 'rating_imdb', 'saw').reverse()
        # films = [obj.check_film() for obj in films_year]
        films_page = Paginator(films, 50)
        pages = films_page.page(1)
        films = pages.object_list
        films_collection = Collection.objects.all()[:10]
        genres = Genre.objects.all()
        context = {
            'films': films,
            'films_collection': films_collection,
            'genres': genres,
            'films_page': films_page,
        }
        return render(request, 'films/index.html', context)


def films_page(request, page=None):
    page = int(page)
    if request.method == 'GET':
        films = Film.objects.all().order_by('year_of_release', 'rating_imdb', 'saw').reverse()
        films_page = Paginator(films, 50)
        films_collection = Collection.objects.all()[:10]
        pages = films_page.page(page)
        films = pages.object_list
        genres = Genre.objects.all()
        context = {
            'films': films,
            'films_collection': films_collection,
            'genres': genres,
            'films_page': films_page,
            'page': page
        }
        return render(request, 'films/index.html', context)


def film(request, film=None):
    film = film
    if request.method == 'GET':
        films = Film.objects.get(name=film)
        context = films.check_film()
    return render(request, 'films/film.html', context)


def genres(request):
    genres_all = Genre.objects.all().order_by('name')
    genres = [obj.check_genres() for obj in genres_all]
    context = {
        'genres': genres,
    }
    return render(request, 'films/genre.html', context)


def genre(request, genre=None):
    pass


def year(request, year=None):
    pass


def country(request, country=None):
    pass


def collections(request):
    pass


def collection(request, collection=None):
    pass


def search(request, search=None):
    pass

filmsatlas/templates/films/film.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{{ name }}
{{ year_of_release }}
{{ duration }}
{{ image }}
{{ description }}
{% for obj in genre %}
    {{ obj }}
{% endfor %}
{% for obj in country %}
    {{ obj }}
{% endfor %}
</body>
</html>

filmsatlas/templates/films/genre.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% if genres %}
<div class="genres">
{% for genre in genres %}
    <br>
    <tr></tr>

    <div class="genre-name">{{ genre.name }}</div>
    <div class="genre-desc">{{genre.desc}}</div>
    <br>
    {% for film in genre.films %}
    <div class="film">
        <div class="film-name">{{film.name}}</div>
    </div>
    {% empty %}
    {% endfor %}
{% empty %}
    <div class="no-genres">No genres</div>
{% endfor %}
</div>
{% endif %}
</body>
</html>

filmsatlas/templates/films/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% if films_collections %}
<div class="films-collections">
    {% for films_collection in films_collections %}
    <div class="films_collection-name">{{ films_collection.name }}</div>
    <div class="films_collection-img"><img src="{{ films_collection.img.url }}"></div>
    <div class="films_collection-desc">{{ films_collection.desc }}</div>
    {% for film in films_collection.check_filmcollection %}
    <div class="film">
        <div class="film-name">{{ film.name }}</div>
        {% if film.year_of_release %}
        <div class="film-year_of_release">{{ film.year_of_release }}</div>
        {% else %}
        <div class="film-year_of_release"></div>
        {% endif %}
        {% if film.image %}
        <div class="film-img"><img src="{{ film.image.url }}"></div>
        {% else %}
        <div class="film-img"></div>
        {% endif %}
        {% if film.check_ganre %}
        <div class="film-genre">
            {% for genre in film.check_ganre %}
            {{ genre.genre.name }}
            {% endfor %}
        </div>
        {% else %}
        <div class="film-genre"></div>
        {% endif %}
        {% if film.check_country %}
        <div class="film-country">
            {% for country in film.check_country %}
            {{ country.country.name }}
            {% endfor %}
        </div>
        {% else %}
        <div class="film-country"></div>
        {% endif %}
    </div>
    {% empty %}
    <div class="films-none">No films</div>
    {% endfor %}
    {% endfor %}
</div>
{% endif %}
{% if films %}
<div class="films">
    {% for film in films %}
    <a href="{% url 'films:film' film.name %}" class="film-{{film.id}}">
        <div class="film">
            <div class="film-name">{{ film.name }}</div>
            {% if film.year_of_release %}
            <div class="film-year_of_release">{{ film.year_of_release }}</div>
            {% else %}
            <div class="film-year_of_release"></div>
            {% endif %}
            {% if film.image %}
            <div class="film-img"><img src="{{ film.image.url }}"></div>
            {% else %}
            <div class="film-img"></div>
            {% endif %}
            {% if film.check_ganre %}
            <div class="film-genre">
                {% for genre in film.check_ganre %}
                {{ genre.genre.name }}
                {% endfor %}
            </div>
            {% else %}
            <div class="film-genre"></div>
            {% endif %}
            {% if film.check_country %}
            <div class="film-country">
                {% for country in film.check_country %}
                {{ country.country.name }}
                {% endfor %}
            </div>
            {% else %}
            <div class="film-country"></div>
            {% endif %}
        </div>
    </a>
    {% empty %}
    <div class="films-none">No films</div>
    {% endfor %}
</div>
{% if films_page %}
{% for page_f in films_page.page_range %}
{% if page == page_f %}
<div class="page-{{page_f}}">{{page_f}}</div>
{% else %}
<a href="{% url 'films:films_page' page_f %}" class="a-page">
    <div class="page-{{page_f}}">{{page_f}}</div>
</a>
{% endif %}
{% endfor %}
{% endif %}
{% endif %}
</body>
</html>